#In the first example, x prints 3
#In the second example, x prints error as it is created within the scope of the do/end block